repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
# export python requirements
- repo: https://github.com/pdm-project/pdm
  rev: 2.12.3 # a PDM release exposing the hook
  hooks:
    - id: pdm-export
      # command arguments, e.g.:
      args: ['-o', 'requirements.txt', '--without-hashes']
      files: ^pdm.lock$
- repo: https://github.com/pdm-project/pdm
  rev: 2.12.3 # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
