stages:
  api:
    cmd: python -m src.api
    deps:
    - src/api.py
    - src/common/utils.py
    outs:
    - data/catalogue-metadata.json
    - data/files-metadata.json
    - data/docs
  datastore:
    cmd: python -m src.datastore
    deps:
    - src/datastore.py
    - src/common/utils.py
    - data/docs
