[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "farm-haystack[file-conversion,inference,pinecone,preprocessing]>=1.22.1",
    "requests>=2.31.0",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0.post1",
    "streamlit>=1.29.0",
    "pre-commit>=3.5.0",
]

requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.18.1",
    "ipdb>=0.13.13",
    "dvc>=3.30.3",
    "dvc-s3>=2.23.0",
]
