[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "llama-index>=0.10.4",
    "llama-index-vector-stores-pinecone>=0.1.1",
    "llama-index-readers-file>=0.1.3",
    "requests>=2.31.0",
    "fastapi>=0.109.2",
    "pydantic-settings>=2.1.0",
    "seaborn>=0.13.2",
    "dateparser>=1.2.0",
    "gunicorn>=21.2.0",
    "uvicorn>=0.27.1",
    "unstructured>=0.12.4",
    "setuptools>=69.1.0",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.21.0",
    "ipdb>=0.13.13",
    "dvc>=3.44.0",
    "dvc-s3>=3.0.1",
    "polars>=0.20.8",
    "pre-commit>=3.6.1",
    "streamlit>=1.31.1",
    "sourcery-cli>=1.15.0",
    "bitsandbytes>=0.42.0",
    "accelerate>=0.27.2",
    "mypy>=1.8.0",
    "pip>=24.0",
    "python-lsp-server>=1.10.0",
    "unstructured[all-docs]>=0.12.4",
]
