[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "llama-index>=0.9.34",
    "llama-hub>=0.0.73",
    "pinecone-client>=3.0.1",
    "requests>=2.31.0",
    "fastapi>=0.109.0",
    "polars>=0.20.5",
    "pydantic-settings>=2.1.0",
    "seaborn>=0.13.1",
    "dateparser>=1.2.0",
    "unstructured[all-docs]>=0.12.0",
    "gunicorn>=21.2.0",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.20.0",
    "ipdb>=0.13.13",
    "dvc>=3.40.1",
    "dvc-s3>=3.0.1",
    "pre-commit>=3.6.0",
    "streamlit>=1.30.0",
    "uvicorn>=0.26.0",
]
