[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "haystack-ai @ git+https://github.com/deepset-ai/haystack.git@main",
    "unstructured-fileconverter-haystack>=0.0.4",
    "chroma-haystack>=0.8.1",
    "requests>=2.31.0",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0.post1",
    "streamlit>=1.29.0",
    "pre-commit>=3.5.0",
    "polars>=0.19.19",
    "more-itertools>=10.1.0",
    "nomic>=2.0.16",
]

requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.18.1",
    "ipdb>=0.13.13",
    "dvc>=3.30.3",
    "dvc-s3>=2.23.0",
]
