[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "llama-index>=0.9.15",
    "llama-hub>=0.0.58",
    "pinecone-client>=2.2.4",
    "requests>=2.31.0",
    "fastapi>=0.105.0",
    "polars>=0.19.19",
    "pydantic-settings>=2.1.0",
    "seaborn>=0.13.1",
    "dateparser>=1.2.0",
    "unstructured>=0.12.0",
    "gunicorn>=21.2.0",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ipython>=8.18.1",
    "ipdb>=0.13.13",
    "dvc>=3.30.3",
    "dvc-s3>=2.23.0",
    "pre-commit>=3.5.0",
    "streamlit>=1.29.0",
    "uvicorn>=0.24.0.post1",
]
