[project]
name = ""
version = ""
description = ""
authors = [
    {name = "cjber", email = "cjberragan@gmail.com"},
]
dependencies = [
    "requests>=2.31.0",
    "ipython>=8.18.1",
    "pandas>=2.1.3",
    "tabula-py>=2.9.0",
    "pypdf>=3.17.1",
    "python-docx>=1.1.0",
    "tabulate>=0.9.0",
    "dvc>=3.30.3",
    "dvc-s3>=2.23.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

