[cdrc-api]
api_url = "https://data.cdrc.ac.uk/api/3/action/current_package_list_with_resources"
login_url = "https://data.cdrc.ac.uk/user/login"

[datastore]
index_name = "cdrc-index"
embed_dim = 1536
chunk_size = 512
chunk_overlap = 100
overwrite = true

[model]
top_k = 10
vector_store_query_mode = "hybrid" # default|sparse|hybrid
alpha = 0.75 # lower values favour sparse vectors, higher values favour dense vectors
response_mode = "no_text"
prompt = """
Below are data profiles for datasets from the CDRC Data Catalogue.
Explain the relevance of these datasets to the following query in under 50 words. Use your own knowledge or the data profile.

---------------------
Query: "{query_str}"

Data profiles:

{context_str}
---------------------
"""
